services:
  - type: web
    name: le-studio-garment
    env: node
    buildCommand: NODE_OPTIONS='--max-old-space-size=4096' npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
