// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytbkcsfzghfwsduphjhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Ymtjc2Z6Z2hmd3NkdXBoamhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzc5MzgsImV4cCI6MjA2ODk1MzkzOH0.8_sQfFtYOpgJfi4RKJx4t5D9-9UHWdLrV8XlkRwzcoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});